"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 25;
let altura = 1.68;
const nacionalidade = 'brasileira';
const colega = ['lucas', 'fernanda', 'julia'];
const tec = ['html', 'css', 'js'];
const notas = [7, 6, 3];
const lista = ['carlos', true, 25];
let idadeAna = 25;
idadeAna: '25';
let dadosApi;
dadosApi = 13;
dadosApi = 'dados';
dadosApi = true;
let curso = 'front-end';
